# Generated by Django 5.1.2 on 2024-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_id', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='faces/')),
                ('document_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
